# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install requirements
        run: sudo apt-get -y install --no-install-recommends \
          git pkg-config meson gcc libtool \
          libgpgme-dev libarchive-dev libcurl4-openssl-dev libssl-dev curl \
          gettext python3 python3-setuptools dash gawk ca-certificates \
          fakeroot xorriso arch-install-scripts e2fsprogs dosfstools \
          gzip mtools squashfs-tools sed zstd

      # Runs a set of commands using the runners shell
      - name: Build pacman
        run: |
          git clone https://git.archlinux.org/pacman.git
          cd pacman
          git checkout $(git describe --tags --abbrev=0)
          meson build
          ninja -C build
          sudo ninja -C build install
          echo "export LD_LIBRARY_PATH=/usr/lib64" >> /etc/environment
          source /etc/environment

      - name: Setup archlinux-keyring
        run: |
          git clone https://gitlab.archlinux.org/archlinux/archlinux-keyring
          cd archlinux-keyring
          make install
          pacman-key --init
          pacman-key --populate archlinux

      - name: Setup pacman
        run: |
          mkdir -p /etc/pacman.d
          curl "https://archlinux.org/mirrorlist/?country=all&protocol=http&protocol=https&ip_version=4&use_mirror_status=on" | sed s/#S/S/g > /etc/pacman.d/mirrorlist
          curl https://raw.githubusercontent.com/u0a266/config/master/etc/pacman.conf > /etc/pacman.conf

      - name: Build archiso
        run: |
          git clone https://gitlab.archlinux.org/archlinux/archiso
          git checkout $(git describe --tags --abbrev=0)
          make install

      - name: Build my distro
        run: |
          sudo mkarchiso -v -w work -o out . 


