# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  schedule:
    - cron: '0 0 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends \
          git pkg-config meson gcc libtool \
          libgpgme-dev libarchive-dev libcurl4-openssl-dev libssl-dev curl \
          gettext python3 python3-setuptools dash gawk ca-certificates \
          fakeroot xorriso e2fsprogs dosfstools \
          gzip mtools squashfs-tools sed zstd 

      # Runs a set of commands using the runners shell
      - name: Setup pacman
        run: |
          git clone https://git.archlinux.org/pacman.git
          cd pacman
          git checkout $(git describe --tags --abbrev=0)
          meson build
          ninja -C build
          sudo ninja -C build install
          export LD_LIBRARY_PATH="/usr/lib64"

      - name: Setup archlinux-keyring
        run: |
          git clone https://gitlab.archlinux.org/archlinux/archlinux-keyring
          cd archlinux-keyring
          git checkout $(git describe --tags --abbrev=0)
          sed -i "s|/local||g" Makefile
          sudo make install
          sudo pacman-key --init
          sudo pacman-key --populate archlinux

      - name: Setup pacman
        run: |
          sudo mkdir -p /etc/pacman.d
          sudo sh -c 'curl "https://archlinux.org/mirrorlist/?country=all&protocol=http&protocol=https&ip_version=4&use_mirror_status=on" | sed s/#S/S/g > /etc/pacman.d/mirrorlist'
          sudo cp pacman.conf /etc/pacman.conf

      - name: Setup archiso
        run: |
          git clone https://gitlab.archlinux.org/archlinux/archiso
          cd archiso
          git checkout $(git describe --tags --abbrev=0)
          sudo make install

      - name: Setup arch-install-scripts
        run: |
          git clone https://git.archlinux.org/arch-install-scripts
          cd arch-install-scripts
          git checkout $(git describe --tags --abbrev=0)
          sudo apt-get -y install --no-install-recommends asciidoc
          sudo make install

      - name: Build my distro
        run: |
          sudo mkarchiso -v -w work -o out . 

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: myarch-x86_64
          path: out

  release:
    runs-on: ubuntu-latest
    needs: [build]

    steps:

      - uses: actions/checkout@v2

      - name: Download artifact
      - uses: actions/download-artifact@v2
        with:
          name: myarch-x86_64

      - name: Create release
      - uses: softprops/action-gh-release@9993ae85344fa542b3edb2533f97011277698cf6
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DATE: $(date +%Y%m)
        with:
          tag_name: $DATE
          name: $DATE
          draft: false
          prerelease: false
          files: out/myarch-*-x86_64.iso




